In [1]:
## Solving a machine learning problem consist of two step
## 1) Training a model using training dataset
## 2) To ask question from trained model

In [2]:
## for large dataset it take more time to train the model
## we can save the model in file
## later on we can use same model to make prediction
## we don't need to train it everytime

In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:green'>Save Model To a File Using Python Pickle</h3>

In [10]:
import pickle

In [11]:
with open('modelpickle1', 'wb') as f:
    pickle.dump(model,f)

In [12]:
with open('modelpickle1', 'rb') as f:
    md = pickle.load(f)

In [14]:
md.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [15]:
from sklearn.externals import joblib

C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [16]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [17]:
joblib.dump(model, 'model1')

['model1']

In [19]:
st = joblib.load('model1')

In [20]:
st.predict([[5500]])

array([927448.63013699])