### DUMMY VARIABLE AND ONE HOT ENCODING PRACTICE

###  Importing libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### loading the dataset

In [2]:
df = pd.read_csv('carprices.csv')

In [3]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [4]:
## Here we can see that price of car is also depend on model of car which is categorical value 
## so we have to create dummy varaible and to do one hot encoding for this

### By using Pandas get_dummies() method

In [6]:
pd.get_dummies(df['Car Model'])

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [7]:
f = pd.get_dummies(df['Car Model']) # storing dummy values into a variable

In [8]:
## now we have to add this dummy variable into dataframe

In [9]:
conct = pd.concat([df,f])

C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [10]:
conct

Age(yrs)  Audi A5  BMW X5              Car Model  Mercedez Benz C class  \
0        6.0      NaN     NaN                 BMW X5                    NaN   
1        3.0      NaN     NaN                 BMW X5                    NaN   
2        5.0      NaN     NaN                 BMW X5                    NaN   
3        2.0      NaN     NaN                 BMW X5                    NaN   
4        4.0      NaN     NaN                 BMW X5                    NaN   
5        5.0      NaN     NaN                Audi A5                    NaN   
6        5.0      NaN     NaN                Audi A5                    NaN   
7        6.0      NaN     NaN                Audi A5                    NaN   
8        8.0      NaN     NaN                Audi A5                    NaN   
9        6.0      NaN     NaN  Mercedez Benz C class                    NaN   
10       7.0      NaN     NaN  Mercedez Benz C class                    NaN   
11       7.0      NaN     NaN  Mercedez Benz C class                    NaN   
12       5.0      NaN     NaN  Mercedez Benz C class                    NaN   
0        NaN      0.0     1.0                    NaN                    0.0   
1        NaN      0.0     1.0                    NaN                    0.0   
2        NaN      0.0     1.0                    NaN                    0.0   
3        NaN      0.0     1.0                    NaN                    0.0   
4        NaN      0.0     1.0                    NaN                    0.0   
5        NaN      1.0     0.0                    NaN                    0.0   
6        NaN      1.0     0.0                    NaN                    0.0   
7        NaN      1.0     0.0                    NaN                    0.0   
8        NaN      1.0     0.0                    NaN                    0.0   
9        NaN      0.0     0.0                    NaN                    1.0   
10       NaN      0.0     0.0                    NaN                    1.0   
11       NaN      0.0     0.0                    NaN                    1.0   
12       NaN      0.0     0.0                    NaN                    1.0   

    Mileage  Sell Price($)  
0   69000.0        18000.0  
1   35000.0        34000.0  
2   57000.0        26100.0  
3   22500.0        40000.0  
4   46000.0        31500.0  
5   59000.0        29400.0  
6   52000.0        32000.0  
7   72000.0        19300.0  
8   91000.0        12000.0  
9   67000.0        22000.0  
10  83000.0        20000.0  
11  79000.0        21000.0  
12  59000.0        33000.0  
0       NaN            NaN  
1       NaN            NaN  
2       NaN            NaN  
3       NaN            NaN  
4       NaN            NaN  
5       NaN            NaN  
6       NaN            NaN  
7       NaN            NaN  
8       NaN            NaN  
9       NaN            NaN  
10      NaN            NaN  
11      NaN            NaN  
12      NaN            NaN

In [11]:
conct = pd.concat([df,f], axis = 'columns')

In [12]:
conct

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [13]:
# now we have to remove Car model column and one dummy variable

In [15]:
final  = conct.drop(['Car Model', 'Mercedez Benz C class'], axis='columns')

In [16]:
final

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [21]:
# Now we need to give x and y for training

In [24]:
x = final.drop('Sell Price($)', axis='columns')

In [26]:
y = final['Sell Price($)']

In [27]:
x

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [28]:
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [29]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### 1) Predict price of a mercedez  benz that is 4 year old  with mileage  45000

In [31]:
model.predict([[45000,4,0,0]])

array([36991.31721061])

### 2) Predict price of a BMWX5 that is 7 year old  with mileage  86000

In [32]:
model.predict([[86000,7,0,1]])

array([11080.74313219])

### 1) Whta is score or accuracey of model

In [34]:
model.score(x,y)

0.9417050937281083

## By using Sklearn

In [35]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
l = LabelEncoder()

In [38]:
df1 = df

In [39]:
l.fit_transform(df1['Car Model'])

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [43]:
df1['Car Model'] = l.fit_transform(df1['Car Model'])

In [44]:
df1

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [45]:
x = df1[['Car Model', 'Mileage', 'Age(yrs)']].values # here we are using values because we want x to be 2d array and not to be a dataframe

In [46]:
y = df1['Sell Price($)']

### Creating dummy variable

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe = OneHotEncoder()

In [50]:
ohe = OneHotEncoder(categorical_features=[0])

In [54]:
x =ohe.fit_transform(x).toarray()

C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [55]:
df.shape

(13, 4)

In [56]:
x

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [57]:
## Here we can see that it created dummy variable

In [58]:
## here we created three dummy varaible column

In [59]:
## we have to drop one dummy variable column

In [60]:
 x = x[:,1:] #[:] means consider all the rows, [1:] means 

In [61]:
x

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [62]:
model.fit(x,y) ##training the model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
model.predict([[1,0,45000,4]])

array([30253.10988495])

In [68]:
model.predict([[0,0,45000,4]])

array([34537.77647335])