### Linear Regression With multiple variable a.ka. multivariate regression

### Importin libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading the data 

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### Here we have to find out price of home that has 
#### 3000 sqr ft area, 3 bedroom, 40year old
#### 2500 sqr ft area, 4 bedroom, 5year old

In [4]:
### we can see that there is missing value in 3rd row
### all the column have linear relationship with target(i.e price) column

### Math concept
### price =  m1 * area + m2 * bedrooms + m3 * age + b
### dependent variable  = price
### Independent variable = area,bedroom,age(features, attributes
### coefficient = m, m2, m3
### b = intercept
### y = m1x1+m2x2+m3x3+b


In [5]:
df.bedrooms.median()

4.0

In [6]:
import math
median  = math.floor(df.bedrooms.median())

In [7]:
median

4

In [8]:
## we can fill this value uing fillna

In [9]:
df.bedrooms.fillna(median)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [10]:
df.bedrooms=df.bedrooms.fillna(median)

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Train linear modrel

#### Creating reg obj 

In [12]:
from sklearn import linear_model

In [13]:
reg = linear_model.LinearRegression()

In [14]:
reg.fit(df[['area', 'bedrooms', 'age']], df.price) # fiting the data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

221323.00186540408

In [17]:
reg.predict([[3000,3,40]]) # Predicting price 

array([498408.25158031])

### price =  m1 * area + m2 * bedrooms + m3 * age + b

In [18]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408

498408.2515740241

In [19]:
reg.predict([[2500,4,5]]) # Predicting price 

array([578876.03748933])

In [20]:
112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.00186540408

578876.0374840142